### ISSUE TITLE
Unable to count committers from some repos on Bitbucket - report incomplete because of undefined author.user object

### ISSUE THREAD

**Issue by robinsmidsrod** [bridgecrewio/redshirts#87]
While trying to build a report of our entire Bitbucket workspace I encounter this bug on some repos, rendering the report incomplete.

```
{
    "error": {
        "message": "Cannot read properties of undefined (reading 'nickname')",
        "stack": "TypeError: Cannot read properties of undefined (reading 'nickname')\n
         at BitbucketRunner.aggregateCommitContributors (/home/portfolio/.nvm/versions/node/v20.12.0/lib/node_modules/@paloaltonetworks/redshirts/dist/vcs/bitbucket/bitbucket-runner.js:18:39)\n
         at BitbucketRunner.processRepo (/home/portfolio/.nvm/versions/node/v20.12.0/lib/node_modules/@paloaltonetworks/redshirts/dist/common/base-runner.js:72:22)\n
         at async Task.task (/home/portfolio/.nvm/versions/node/v20.12.0/lib/node_modules/@paloaltonetworks/redshirts/dist/common/base-runner.js:45:25)"
    }
}
```

From what I can tell there is a problem with this block:

```
            const newCommit = {
                username: author.user.nickname,
                email: email || author.raw,
                commitDate: date,
            };
```

It seems you're referencing the `nickname` property, but `author.user` is undefined, leading to this exception. Catching this error and outputting `author.raw` to the debug log seems wise, and possibly adding a list of unrecognized/ignored authors to the output in some way would be helpful.

**Comment by robinsmidsrod** [comment]
For reference, one of the git commit author lines in question that most likely triggered this bug had just this value in it: `FluxCD <>`

So there was no email to extract.

**Comment by robinsmidsrod** [comment]
@mikeurbanski1 @kartikp10 I noticed it's a while since there was any movement in this repo. Just hoping this bug won't be lost in the void, since it's being used to count our credit usage in Prisma Cloud. It's quite hard for us to reduce the usage when we don't know which of our developers are counted double because they don't consistently use a single email for their commit author value.
